import { Inter } from "next/font/google";
import Head from "next/head";
import { VscColorMode } from "react-icons/vsc";
import { AiFillGithub, AiFillLinkedin, AiFillYoutube } from "react-icons/ai";
import Image from "next/image";
import avatar from "../public/avatar.jpg";
import OCLogo from "../public/OC_logo.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Logan Lee Brown Portfolio</title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white dark:bg-gray-500">
        <section>
          <nav className="py-10 px-5 mb-12 flex justify-between">
            <h1 className="text-xl">Early Portfolio Alpha</h1>
            <ul className="flex items-center">
              <li>
                <VscColorMode
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="Resume"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 shadow rounded-xl">
            <h2 className="text-5xl text-transparent bg-clip-text py-3 bg-gradient-to-t from-teal-600 to-gray-300 font-medium md:text-6xl dark:from-teal-300 dark:to-white">
              Logan Brown
            </h2>
            <h3 className="text-2xl md:text-3xl py-2">Full Stack Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
              I am a creative software engineer with multiple years of
              experience in industry leading software environments. I like to
              build creative and powerful products that improve the user
              experience.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-300">
            <Link href="https://www.linkedin.com/in/logan-lee-brown/">
              <AiFillLinkedin />
            </Link>
            <Link href="https://github.com/LoganLeeBrown">
              <AiFillGithub />
            </Link>
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 mb-10 md:h-96 md:w-96 overflow-hidden">
            <Image
              src={avatar}
              layout="fill"
              objectFit="cover"
              alt="meaningful"
            />
          </div>
        </section>

        <section className="px-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Experience</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              As an engineer I am led by curiosity. I jumped into the healthcare
              software industry with the goal of helping the public in an area
              where they needed it most. Outside of the 9-5 I continue to
              develop my skills by learning every piece of technology that
              catches my eye.
            </p>
          </div>
          <div className="lg:flex gap-10 lg:justify-center">
            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:bg-white basis-1/3">
              <Image src={OCLogo} alt="meaningful" objectFit="contain" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Industry Experience
              </h3>
              <p className="py-2">
                Back-End REST layer development on industry leading Electronic
                Health Record provider.
              </p>
              <h4 className="py-4 text-teal-600">Tools Used</h4>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">Jax-RS</p>
              <p className="text-gray-800 py-1">Maven</p>
              <p className="text-gray-800 py-1">Oracle DB</p>
              <p className="text-gray-800 py-1">Git</p>
            </div>
            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:bg-white basis-1/3">
              <Image src={code} width={100} height={100} alt="meaningful" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">Llorum Llorum yououoiujiuouiouoiuojo</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">one</p>
              <p className="text-gray-800 py-1">two</p>
              <p className="text-gray-800 py-1">three</p>
            </div>
            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:bg-white basis-1/3">
              <Image
                src={consulting}
                width={100}
                height={100}
                alt="meaningful"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">Llorum Llorum yououoiujiuouiouoiuojo</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">one</p>
              <p className="text-gray-800 py-1">two</p>
              <p className="text-gray-800 py-1">three</p>
            </div>
          </div>
        </section>

        <section className="px-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">
              &lt;PersonalProjects&gt;
            </h3>
            <p className="py-2 dark:text-gray-300">
              Llorum Llorum yououoiujiuouiouoiuojo
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap sm:flex-1">
            <div className="basis-1/3 relative">
              <Link href="https://chirp-ten-henna.vercel.app/">
                <div className="absolute h-full w-full overflow-hidden bg-[hsl(0,0%,98.4%,0.2)] bg-fixed opacity-0 transition duration-300 ease-in-out hover:opacity-100 rounded-lg">
                  <span className="absolute my-4 mx-4 text-black bg-white bg-opacity-50 rounded-full px-2 font-medium">
                    Chirp
                  </span>
                </div>
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web1}
                  alt="meaningful"
                />
              </Link>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
