import { Inter } from "next/font/google";
import Head from "next/head";
import { VscColorMode } from "react-icons/vsc";
import { AiFillGithub, AiFillLinkedin, AiFillYoutube } from "react-icons/ai";
import Image from "next/image";
import avatar from "../public/avatar.jpg";
import OCLogo from "../public/OC_logo.png";
import code from "../public/code.png";
import universityArkansas from "../public/UniversityArkansasLogo.png";
import web1 from "../public/web1.png";
import { useState } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Logan Lee Brown Portfolio</title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <section className="bg-[#3FEEE6] dark:bg-[#0B0C10] py-2">
          <nav className="py-10 px-5 mb-12 flex justify-between">
            <h1 className="text-xl dark:text-white">Early Portfolio Alpha</h1>
            <ul className="flex items-center dark:text-white">
              <li>
                <VscColorMode
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="Resume"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-left p-10 m-10 shadow-xl rounded-xl bg-[#97CAEF] dark:bg-[#45A29E]">
            <h2 className="text-5xl py-3 text-[#CAFAFE] bg:text-[#66FCF1] font-extrabold md:text-6xl">
              Logan Brown
            </h2>
            <h3 className="text-2xl font-bold md:text-3xl py-2">
              Full Stack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg">
              I am a creative software engineer with multiple years of
              experience in industry leading software environments. I like to
              build creative and powerful products that improve the user
              experience.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-300">
            <Link href="https://www.linkedin.com/in/logan-lee-brown/">
              <AiFillLinkedin />
            </Link>
            <Link href="https://github.com/LoganLeeBrown">
              <AiFillGithub />
            </Link>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 mb-10 md:h-96 md:w-96 overflow-hidden">
            <Image
              src={avatar}
              layout="fill"
              objectFit="cover"
              alt="meaningful"
            />
          </div>
        </section>

        <section className="px-10 bg-[#55BCC9] dark:bg-[#1F2833] py-96">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Experience</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              As an engineer I am led by curiosity. I jumped into the healthcare
              software industry with the goal of helping the public in an area
              where they needed it most. Outside of the 9-5 I continue to
              develop my skills by learning every piece of technology that
              catches my eye.
            </p>
          </div>
          <div className="lg:flex gap-10 lg:justify-center">
            <div className="flex flex-col text-center shadow-xl p-10 rounded-xl my-10 bg-white basis-1/3">
              <div className="mx-auto basis-1/3">
                <Image src={OCLogo} alt="meaningful" objectFit="contain" />
              </div>
              <div className="basis-1/3">
                <h3 className="text-lg font-medium pt-8 pb-2">
                  Industry Experience
                </h3>
                <p className="py-2">
                  Back-End REST layer development on industry leading Electronic
                  Health Record provider.
                </p>
              </div>
              <div className="basis-1/3">
                <h4 className="py-4 text-teal-600">Tools Used</h4>
                <p className="text-gray-800 py-1">
                  Java, Jax-RS, Maven, Oracle DB, Git
                </p>
              </div>
            </div>
            <div className="flex flex-col text-center shadow-xl p-10 rounded-xl my-10 bg-white basis-1/3">
              <div className="basis-1/3">
                <Image src={code} objectFit="contain" alt="meaningful" />
              </div>
              <div className="basis-1/3">
                <h3 className="text-lg font-medium">Personal Projects</h3>
                <p className="">
                  The best way to learn a new technology is to build something
                  with it. I like to build projects on my own using technology
                  that interests me.
                </p>
              </div>
              <div className="basis-1/3">
                <h4 className=" text-teal-600">Tools used</h4>
                <p className="text-gray-800">
                  Typescript, Javascript, NextJs, React, Vercel, Clerk
                </p>
              </div>
            </div>
            <div className="flex flex-col text-center shadow-xl p-10 rounded-xl my-10 bg-white basis-1/3">
              <div className="mx-auto basis-1/3">
                <Image
                  src={universityArkansas}
                  objectFit="contain"
                  alt="meaningful"
                />
              </div>
              <div className="basis-1/3">
                <h3 className="text-lg font-medium pt-8 pb-2">
                  University of Arkansas
                </h3>
              </div>
              <div className="basis-1/3">
                <p className="py-2">Bachelor&apos;s Degree</p>
                <p className="text-gray-800 py-1">Computer Science</p>
                <p className="text-gray-800 py-1">ACM President</p>
                <p className="text-gray-800 py-1"></p>
              </div>
            </div>
          </div>
        </section>

        <section className="px-10 bg-[#CAFAFE] dark:bg-[#C5C6C7] py-96">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">
              &lt;PersonalProjects&gt;
            </h3>
            <p className="py-2 ">Llorum Llorum yououoiujiuouiouoiuojo</p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap sm:flex-1">
            <div className="basis-1/3 relative">
              <Link href="https://chirp-ten-henna.vercel.app/">
                <div className="absolute h-full w-full overflow-hidden bg-[hsl(0,0%,98.4%,0.2)] bg-fixed opacity-0 transition duration-300 ease-in-out hover:opacity-100 rounded-lg">
                  <span className="absolute my-4 mx-4 text-black bg-white bg-opacity-50 rounded-full px-2 font-medium md:text-xl">
                    Chirp
                  </span>
                </div>
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web1}
                  alt="meaningful"
                />
              </Link>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
